version: "3.8"

services:
  app:
    build: .
    container_name: news_classifier_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models:ro
    restart: unless-stopped
